name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install node_modules
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npx vitest run

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: npm

      - name: Install node_modules
        run: npm ci

      - name: Check Prettier
        run: npm run format:check
